### ISSUE TITLE
New doctrine/dbal polyfills have side effects

### ISSUE THREAD

**Issue by dFayet** [getsentry/sentry-symfony#484]
Since sentry/sentry-symfony version 4.1.0,  new doctrine/dbal polyfills were added:

https://github.com/getsentry/sentry-symfony/blob/b2500fb71a7acef734ba72f8d0f98ee530cf8174/src/aliases.php#L97-L120
Related PR: #423 

This has the effect of misleading code based on the existence, or not, of these doctrine/dbal v2 interfaces.
As basing the detection only on that is maybe not a great idea, creating polyfill for 3rd party library seems to be quite odd too.

**Comment by Jean85** [comment]
I agree that this approach is not great; we did something similar with the Symfony classes, in the first part of the file, but in that case we declared completely new names to avoid clashing.

@ste93cry do you think that we can do the same here?

**Comment by ste93cry** [comment]
@Jean85 this looks (at least partially) solved by #527, right? As far as I see only two aliases remain

**Comment by Jean85** [comment]
It should. Both aliases are against a classname that it's our own, so we shouldn't have this issue anymore.

@dFayet can you test our `develop` branch to confirm?

**Comment by dFayet** [comment]
@Jean85 it reduces the numbers of errors possible, but it does not solve the issue as the alias `class_alias(ExceptionConverterDriverInterface::class, LegacyExceptionConverterDriverInterface::class); ` is still here.

**Comment by ste93cry** [comment]
>it does not solve the issue as the alias

Yep, that was my thinking. But to be honest I don't see how we could get rid of the remaining ones, we have to implement the interface and in this case it's Symfony not making his own business

**Comment by dFayet** [comment]
> it's Symfony not making his own business
I don't think this is Symfony's business here, we have problems with Doctrine.

Is the alias needed somewhere else than in `Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriver` ?
If no, wouldn't it be possible to have 2 implementations like `Dbal2TracingDriver` and `Dbal3TracingDriver` (with abstraction, trait, ...)?

**Comment by Jean85** [comment]
@dFayet you're welcome to try it if you want, PR are welcome.
You should target `develop` though, since #527 changed so much already there.
