### ISSUE TITLE
Wrong MySQL platform is being returned by the TracingDriverForV32

### ISSUE THREAD

**Issue by SanderVerkuil** [getsentry/sentry-symfony#734]
### Environment

What version are you running? Etc.
- **php**: PHP 8.2.7 
- **symfony**: 5.4
- **sentry/sentry-symfony**: 4.9.1
- **doctrine/dbal**: 3.6.3
- **doctrine/orm**: 2.15.2

### Steps to Reproduce

1. Run `bin/console doctrine:schema:update --complete --dump-sql`.

### Expected Result

The command should succeed

### Actual Result

An exception occurred that the platform does not support the `json` type.

---

When building the connection, doctrine is fetching the DatabasePlatform. This calls the `detectDatabasePlatform` method, which chooses whether it will call the method `createDatabasePlatformForVersion` or the method `getDatabasePlatform`. 

The `version` is fetched with the method `getDatabasePlatformVersion()`. If the driver is not an instance of the `VersionAwarePlatformDriver` interface, it always returns `null`, which then calls the `getDatabasePlatform` method, which returns the default `MySqlPlatform`, which does not support the `json` type.

It should have returned the `MySQL80Platform` in my case.

The fix appears to be as simple as implementing the `VersionAwarePlatformDriver` on the `TracingDriverForV32` class, but in [this comment](https://github.com/getsentry/sentry-symfony/pull/731#issuecomment-1594921405) the choice was made to not implement the deprecated interface, which makes sense.

Though I do not fully understand why the `VersionAwarePlatformDriver` was deprecated, as the comment itself says that `All drivers will have to be aware of the server version in the next major release.`, which leads me to believe that as of the next major version of the `doctrine/dbal`, the `createDatabasePlatformForVersion` will be moved to the `Driver` interface... This makes sense, but then the `TracingDriverForV32` should still implement the `VersionAwarePlatformDriver` right? At least until the next major version?

**Comment by cleptric** [comment]
We fixed this in https://github.com/getsentry/sentry-symfony/pull/731, with version 4.9.1 being released today that contains the change. `TracingDriverForV32` does contain `createDatabasePlatformForVersion` now, but we did not implement the interface to fix triggering deprecation warnings (See https://github.com/getsentry/sentry-symfony/issues/579).

So to confirm, you already updated to 4.9.1, and the issue persists?

**Comment by cleptric** [comment]
Ok, so I understand we should also add `getDatabasePlatform`, correct?

**Comment by SanderVerkuil** [comment]
Yes, I've updated to 4.9.1 and the issue persists. The reason is that the `Connection` class calls either the `createDatabasePlatformForVersion` or the `getDatabasePlatform` method. As the `version` is set to `null`, because the `driver` is not an instance of the `VersionAwarePlatformDriver`, the method `getDatabasePlatform` is called, which returns the `MySQLPlatform`, instead of the `MySQL80Platform`.

**Comment by SanderVerkuil** [comment]
The `TracingDriverForV3` does implement the `VersionAwarePlatformDriver`, which ensures that the correct method is called, but the `TracingDriverForV32` is not called.

This might be an issue in the `doctrine/dbal` though, that the `VersionAwarePlatformDriver` should not have been made deprecated just yet, as it is still required for the correct functioning of the system.

The `getDatabasePlatform` is already present, but that returns the `MySQLPlatform` according the the `AbstractMySQLDriver`. The only correct way I see is to let the `TracingDriverForV32` implement the `VersionAwarePlatformDriver`, which will trigger deprecations again, but I think that those deprecations just aren't correct 🤷

**Comment by cleptric** [comment]
> Maybe we should revert all the changes and just tell everyone to suppress this deprecation using the [baseline](https://symfony.com/doc/current/components/phpunit_bridge.html#baseline-deprecations).

I would like to go this route for now. I rather have some deprecation warnings than a broken SDK. I'll get the PR ready.

**Comment by cleptric** [comment]
@ste93cry Mind copying your comment over to #579? I reopened the issue.

@SanderVerkuil This issue was fixed in [4.9.2](https://github.com/getsentry/sentry-symfony/releases/tag/4.9.2), sorry for the trouble!

**Comment by SanderVerkuil** [comment]
@cleptric Yep, it has indeed been fixed! Thanks for the quick iteration and fast feedback ❤️

**Comment by morozov** [comment]
@ste93cry if you believe that there is an upgrade issue that might/should be addressed in the DBAL, please file an issue with [doctrine/dbal](https://github.com/doctrine/dbal) and provide the relevant details there.
